### ISSUE TITLE
Add MAINTAINERS file (or CODEOWNERS)

### ISSUE THREAD

**Issue by magicDGS** [samtools/htsjdk-next-beta#7]
It would be nice to have a `MAINTAINERS.md` file for whomever that wants to contact maintainers (or ask for feedback on PR, issues, etc) have a place to look at it; and also for keep track of how governance change over time.

I found also an interesting feature in GitHub, the ["code owners"](https://blog.github.com/2017-07-06-introducing-code-owners/), which automatically request review for maintainers if specify in a `CODEOWNERS` file (in the root directory or `.github/`). I think that is worth to look at it, and keep in the `.github/` folder this file with the templates for issues/PRs. More info here: https://blog.github.com/2017-07-06-introducing-code-owners/

What do you thing @lbergelson, @jacarey, @tfenne?

**Comment by lbergelson** [comment]
👍 to adding a maintainers file.  I'll do that.  I think github's auto suggest for reviewers is actually working pretty well without the codeowners file.  It seems to be based on the git history.  Maybe once we have a more complicated project with different modules that have very differen knowledge bases it might be worth it.  It's a neat feature that I didn't know about.
