### ISSUE TITLE
Setup sane labels for issue tracking (better backlog)

### ISSUE THREAD

**Issue by magicDGS** [samtools/htsjdk-next-beta#8]
I propose to have a labeling scheme using `Status`, `Type` and `Priority` tags for each issue and PR, similar to the scheme proposed in https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
In addition, we can have a backlog project (https://github.com/samtools/htsjdk-next-beta/projects) to track all the issues, with some automatization. 

I can setup this soon, and proposals are welcome for it. My idea about the labeling scheme is:
* __Status__: `Abandoned` (discarded issues), `Blocked` (need some work or upstream changes), `In Progress` (someone took over the issue or there is already a PR), `Completed` (finished ones - may be still open to ask for feedback), `On Hold` (work in progress to take a decision or still not in a state for review if a PR), `Review Needed` (for PRs that does not have a review yet). Some optional ones that I have consider but I don't think that would be important are `Under Review` (already reviewed by some maintainer and waiting for the final decision/feedback from the PR author), `Available` (for issues that are available for implementation - they would be nice for contributors to pick issues to work on), `Pending` (for issues that needs some discussion to include in the backlog, either because they are controversial or breaking backwards compatibility).
* __Type__: `Bug`, `Enhancement`, `API` (issues that are related with API changes), `Maintenance` (DevOps, code reafactor without change, cleanup), `Question` (for user/collaborators requested help), `Test` (related with increasing test coverage or adding edge test cases).
* __Priority__:  `Critical` (to pinpoint quickly bugs, security concerns, wrong implementations; this might be redundant with `Type:Bug`, but upgrading a library might be critical and marked as `Type:Maintenance`), `High`, `Medium`, `Low`.

As we would implement a multi-module project, we have several options for tracking module-issues:
* Project backlog per-module. That will be a `Core backlog`, `CRAM backlog`, etc. in the repo projects (https://github.com/samtools/htsjdk-next-beta/projects)
* Add a third bidimensional label `Module`, to specify `Module:Core`, `Module:CRAM`, etc. This label could be an optional label or a required one (adding `Module:All` for things affecting all modules, such as DevOps).
* Allow extra labels prefixed with `~` to appear at the end of the list of labels, and indicate that they are not required labels (e.g., `~cram` will identify issues related with CRAM, but it is not required that it is included).

**Comment by lbergelson** [comment]
@magicDGS I agree that we should be doing a better job of labeling things than we did in htsjdk.  This scheme seems sane but kind of complicated.  I'm willing to give it a shot but I suspect it might get out of date very quickly unless everyone commits to 

1.  doing triage of new issues very promptly
2.  keeping their own issues and issues they update in sync.   

Priorities could maybe be simplified to: 
- Critical, i.e. someone must do this before the next release or even create a special release just for this
- blank - this is standard priority, stuff we actively plan on doing
- Low: this is a good idea but the maintainers probably aren't going to drive it forward without someone really championing it

**Comment by magicDGS** [comment]
I could understand the complication of the labels about the **Status**, which can be complicated. Maybe we can get rid of it and just keep the ones for **Type** and **Priority**. I agree that having 4 labels for priority might be a lot; so your proposal of 3 sounds good to me, but assigning a `Priority:Normal` to the standard priority. I prefer to always mark the issues with a label to easily track them, and pinpoint things that does not have a label as not triaged. If we get rid of the **Status** category, which could be tracked in the project backlog (TODO/IN PROGRESS/DONE/ABANDONED - almost all can be automatized in GitHub projects, minimizing the needed triage), we can add the **Module** label to easily track stuff that is related with core, cram, base-API, etc.

So the proposal as it is now in my head is:

* All issues/PRs related with code/docs (not questions) should be in a GitHub project (backlog), with the `TODO`, `IN PROGRESS`, `DONE` and `ABANDONED`  columns. They will be automatized, and our responsibilty as maintainers is to triage every issue
* Every issue/PR requires a `Type`, `Priority` and `Module` label - like that, it would be easier to track different issues by collaborators and maintainers
* Assignation of issues should be a common practice to show the community who is working on them - if we as maintainers pick an issue to work on, we should mark them; if any member claims the issue for them, we can assign it to them up to certain time.

To maintain properly this scheme, although we can do it as we feel like, we can assign every week a maintainer to triage/add labels to the new issues by the end of the week. We can have a spreadsheet (GoogleDocs) to schedule it: is once per month too much for adding labels and triage issues to maintain a sane structured project?

By the way, all this should be in the contributors guide to explain how the API/code evolves and is maintain...

**Comment by magicDGS** [comment]
And I forgot to mention: should we have per-quartier milestones to show the community how the roadmap is scheduled and what is achieved within that time?

**Comment by tfenne** [comment]
I like the updated proposal @magicDGS.  I'm not sure how automatable any of this is but I think it would be really nice if:

1. We could have a `AWAITING TRIAGE` or similar column in the project where all new issues land.
2. We could have new issues and PRs default to `Priority:Normal` unless otherwise specified, to minimize the triage effort

Also, my experience with `Type` for issues is that you always end up with some that don't fit into any of the existing categories.  Rather than having a proliferation of `Type`s as we come across these, how do you feel about having `Type:Other`?

**Comment by lbergelson** [comment]
@magicDGS Would you like to set up a github project and add the various labels so we can try this out?

**Comment by lbergelson** [comment]
Thinking about it more, we might want statuses about review for PRs like you initially had, but we can add those in later when it becomes necessary.

**Comment by magicDGS** [comment]
I started setting up the project/labels and projects to try this out.

@tfenne - as far as I know, in GitHub it is not possible automatic addition to a project nor adding default labels, but I will search for a solution. I like the idea of `Type:Other` for the case of not fitting into any type (if we see that this kind of issues are increasing, maybe we should add a new type for them).

**Comment by magicDGS** [comment]
More about project board automatization: https://help.github.com/articles/about-automation-for-project-boards/

**Comment by magicDGS** [comment]
@lbergelson - I though that maybe it is a better idea to have a "project backlog" and a "PR backlog": one for only the issues and another just for the pull-requests; then, it isn't needed a `Status` label...

**Comment by lbergelson** [comment]
It seems like this is implemented.  Should we close it? @magicDGS

**Comment by magicDGS** [comment]
Yes - we can play around with other labels/projects/milestones later, and discuss them on slack.
